baseURL = 'https://quanghieu31.github.io/'
languageCode = 'en-us'
title = 'Home'
theme = 'hugo-coder-main'
enableEmoji = true

[params]
  author = 'Hieu Nguyen'
  favicon_32 = "images/favicon.ico"
  colorScheme = "auto"
  avatarURL = "images/about/me.jpg"
  avatarabout = "images/about/me1.jpg"
  customCSS = ["css/custom.css"]

[menu]
[[menu.main]]
  identifier = 'About'
  name = 'About'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight=1
[[menu.main]]
  identifier = 'Posts'
  name = 'Posts'
  pre = "<i class='fa fa-heart'></i>"
  url = '/posts/'
  weight=2

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/quanghieu31"

[[params.social]]
name = "Kaggle"
icon = "fa fa-2x fa-brands fa-kaggle"
weight = 2
url = "https://www.kaggle.com/hieunguyendq"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-brands fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/hieunguyen31/"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-envelope"
weight = 4
url = "mailto:doanquanghieu.nguyen@gmail.com"

[minify]
  disable = ["CSS"]

[partials]
  head = "partials/head/custom-styles.html"
